// vocab_kana_data.js
// Japanese → Bahasa Indonesia vocabulary flashcard data.
// Each entry: { front, answers[], type }
// answers[] accepts multiple correct translations (case-insensitive).

// answers[] supports multiple accepted translations per card.
// Add more entries following the same shape.
const VOCAB_KANA = [
  { front: "わたし", answers: ["saya", "aku"] },
  { front: "あなた", answers: ["anda"] },
  { front: "あのひと", answers: ["orang itu"] },
  { front: "あのかた", answers: ["orang itu"] },
  { front: "~さん", answers: ["saudara ~"] },
  { front: "~ちゃん", answers: ["anak ~"] },
  { front: "~じん", answers: ["orang ~"] },
  { front: "せんせい", answers: ["guru"] },
  { front: "きょうし", answers: ["guru"] },
  { front: "ごくせい", answers: ["mahasiswa"] },
  { front: "かいしゃいん", answers: ["karyawan"] },
  { front: "~のしゃいん", answers: ["karyawan ~"] },
  { front: "ぎんこういん", answers: ["pegawai bank"] },
  { front: "いしゃ", answers: ["dokter"] },
  { front: "けんきゅうしゃ", answers: ["peneliti"] },
  { front: "だいがく", answers: ["universitas"] },
  { front: "びょういん", answers: ["rumah sakit"] },
  { front: "だれ", answers: ["siapa"] },
  { front: "どなた", answers: ["siapa"] },
  { front: "~さい", answers: ["~ tahun"] },
  { front: "なんさい", answers: ["umur berapa"] },
  { front: "おいくつ", answers: ["umur berapa"] },
  { front: "はい", answers: ["iya"] },
  { front: "いいえ", answers: ["tidak"] },
  { front: "はじめまして", answers: ["perkenalkan"] },
  { front: "~からきました", answers: ["datang dari ~"] },
  { front: "どうぞよろしくおねがいします", answers: ["salam kenal"] },
  { front: "しつれいですか", answers: ["permisi"] },
  { front: "おなまえわ", answers: ["siapa namanya?"] },
  { front: "こちらわ ~さん です", answers: ["ini saudara ~"] },
  { front: "アメリカ", answers: ["amerika"] },
  { front: "イギリス", answers: ["inggris"] },
  { front: "インド", answers: ["india"] },
  { front: "インドネシア", answers: ["indonesia"] },
  { front: "カンコク", answers: ["korea selatan"] },
  { front: "タイ", answers: ["thailand"] },
  { front: "チュウゴク", answers: ["cina"] },
  { front: "ドイツ", answers: ["jerman"] },
  { front: "ニホン", answers: ["jepang"] },
  { front: "ブラジル", answers: ["brazil"] },
  { front: "これ", answers: ["ini"] },
  { front: "それ", answers: ["itu"] },
  { front: "あれ", answers: ["itu"] },
  { front: "この ~", answers: ["~ ini"] },
  { front: "その ~", answers: ["~ itu"] },
  { front: "あの ~", answers: ["~ itu"] },
  { front: "ほん", answers: ["buku"] },
  { front: "じしょ", answers: ["kamus"] },
  { front: "ざっし", answers: ["majalah"] },
  { front: "しんぶん", answers: ["koran"] },
  { front: "ノート", answers: ["buku tulis"] },
  { front: "てちょう", answers: ["buku agenda"] },
  { front: "めいし", answers: ["kartu nama"] },
  { front: "カード", answers: ["kartu"] },
  { front: "えんぴつ", answers: ["pensil"] },
  { front: "ボールペン", answers: ["bolpoin"] },
  { front: "シャープペンシル", answers: ["pensil mekanik"] },
  { front: "かぎ", answers: ["kunci"] },
  { front: "とけい", answers: ["jam"] },
  { front: "かさ", answers: ["payung"] },
  { front: "かばん", answers: ["tas"] },
  { front: "CD", answers: ["CD"] },
  { front: "テレビ", answers: ["TV"] },
  { front: "ラジオ", answers: ["radio"] },
  { front: "カメラ", answers: ["kamera"] },
  { front: "コンピューター", answers: ["komputer"] },
  { front: "くるま", answers: ["mobil"] },
  { front: "いす", answers: ["kursi"] },
  { front: "つくえ", answers: ["meja"] },
  { front: "チョコレート", answers: ["coklat"] },
  { front: "コーヒー", answers: ["kopi"] },
  { front: "みやげ", answers: ["oleh-oleh"] },
  { front: "くつ", answers: ["sepatu"] },
  { front: "ネクタイ", answers: ["dasi"] },
  { front: "ワイン", answers: ["anggur"] },
  { front: "えいご", answers: ["bahasa Inggris"] },
  { front: "にほんご", answers: ["bahasa Jepang"] },
  { front: "~ご", answers: ["bahasa ~"] },
  { front: "ここ", answers: ["sini"] },
  { front: "そこ", answers: ["situ"] },
  { front: "あそこ", answers: ["sana"] },
  { front: "どこ", answers: ["dimana"] },
  { front: "こちら", answers: ["sini"] },
  { front: "そちら", answers: ["situ"] },
  { front: "あちら", answers: ["sana"] },
  { front: "どちら", answers: ["dimana"] },
  { front: "きょうしつ", answers: ["ruang kelas"] },
  { front: "しょくどう", answers: ["ruang makan"] },
  { front: "じむしょ", answers: ["kantor"] },
  { front: "かいぎしつ", answers: ["ruang rapat"] },
  { front: "うけつけ", answers: ["meja informasi"] },
  { front: "ロビー", answers: ["lobi"] },
  { front: "へや", answers: ["kamar"] },
  { front: "トイレ", answers: ["toilet"] },
  { front: "おてあらい", answers: ["toilet"] },
  { front: "かいだん", answers: ["tangga"] },
  { front: "エレベーター", answers: ["lift"] },
  { front: "エスカレーター", answers: ["eskalator"] },
  { front: "じどうはんばいき", answers: ["mesin jual otomatis"] },
  { front: "でんわ", answers: ["telepon"] },
  { front: "おくに", answers: ["negara"] },
  { front: "かいしゃ", answers: ["perusahaan"] },
  { front: "うち", answers: ["rumah"] },
  { front: "うりば", answers: ["toko"] },
  { front: "ちか", answers: ["basement"] },
  { front: "~かい", answers: ["lantai ~"] },
  { front: "~がい", answers: ["lantai ~"] },
  { front: "なんがい", answers: ["lantai berapa"] },
  { front: "~えん", answers: ["~ yen"] },
  { front: "いくら", answers: ["berapa"] },
  { front: "ひゃく", answers: ["ratus"] },
  { front: "せん", answers: ["ribu"] },
  { front: "まん", answers: ["puluh ribu"] },
  { front: "なん", answers: ["apa"] },
  { front: "そう", answers: ["begitu"] },
  { front: "あのう", answers: ["eee..."] },
  { front: "どうぞ", answers: ["silahkan"] },
  { front: "すみません", answers: ["permisi"] },
  { front: "どうも", answers: ["terimakasih"] },
  { front: "いらっしゃいませ", answers: ["selamat datang"] },
  { front: "じゃ", answers: ["kalau begitu"] },
  { front: "~を みせて ください", answers: ["tolong perlihatkan ~"] },
  { front: "~を ください", answers: ["minta ~"] },
  { front: "どうも ありがとう ございます", answers: ["terimakasih banyak"] },
  { front: "そう ですか", answers: ["o begitu"] },
  { front: "ちがいます", answers: ["bukan begitu"] },
  { front: "これから おせわに なります", answers: ["mulai sekarang mohon bantuannya"] },
  { front: "こちらこそ どうぞ よろしく おねがいします", answers: ["ya, sama-sama"] },
  { front: "イタリア", answers: ["italia"] },
  { front: "スイス", answers: ["swiss"] },
  { front: "フランス", answers: ["perancis"] },
  { front: "ジャカルタ", answers: ["jakarta"] },
  { front: "バンコク", answers: ["bangkok"] },
  { front: "ベルリン", answers: ["berlin"] },
  { front: "おくじょう", answers: ["atap", "rooftop"] },
  { front: "ゆうえんち", answers: ["tempat hiburan", "taman hiburan"] },
  { front: "レストラン", answers: ["restoran"] },
  { front: "もよおしものかいじょう", answers: ["tempat acara", "tempat pertunjukan"] },
  { front: "めがね", answers: ["kacamata"] },
  { front: "スポーツようひん", answers: ["perlengkapan olahraga"] },
  { front: "りょこうようひん", answers: ["perlengkapan bepergian"] },
  { front: "こどもふく", answers: ["pakaian anak"] },
  { front: "おもちゃ", answers: ["mainan"] },
  { front: "ぶんぼうぐ", answers: ["alat tulis"] },
  { front: "かぐ", answers: ["mebel", "furnitur"] },
  { front: "しょっき", answers: ["peralatan makan", "alat makan"] },
  { front: "でんきせいひん", answers: ["peralatan elektronik", "barang elektronik"] },
  { front: "しんしふく", answers: ["pakaian pria"] },
  { front: "ふじんふく", answers: ["pakaian wanita"] },
  { front: "くつ", answers: ["sepatu"] },
  { front: "アクセサリー", answers: ["aksesoris", "perhiasan"] },
  { front: "けしょうひん", answers: ["kosmetik"] },
  { front: "しょくひん", answers: ["bahan makanan", "makanan"] },
  { front: "ちゅうしゃじょう", answers: ["tempat parkir"] },
  { front: "おきます", answers: ["bangun"] },
  { front: "ねます", answers: ["tidur"] },
  { front: "はたらきます", answers: ["bekerja"] },
  { front: "やすみます", answers: ["libur", "istirahat", "beristirahat"] },
  { front: "べんきょうします", answers: ["belajar"] },
  { front: "おわります", answers: ["selesai", "berakhir"] },
  { front: "デパート", answers: ["toserba", "department store"] },
  { front: "ぎんこう", answers: ["bank"] },
  { front: "ゆうびんきょく", answers: ["kantor pos"] },
  { front: "としょかん", answers: ["perpustakaan"] },
  { front: "びじゅつかん", answers: ["museum seni", "gedung kesenian"] },
  { front: "いま", answers: ["sekarang"] },
  { front: "~じ", answers: ["jam ~", "pukul ~"] },
  { front: "~ふん", answers: ["~ menit"] },
  { front: "~ぷん", answers: ["~ menit"] },
  { front: "はん", answers: ["setengah"] },
  { front: "なんじ", answers: ["jam berapa", "pukul berapa"] },
  { front: "なんぷん", answers: ["menit berapa", "berapa menit"] },
  { front: "ごぜん", answers: ["pagi", "AM"] },
  { front: "ごご", answers: ["siang", "sore", "PM"] },
  { front: "あさ", answers: ["pagi"] },
  { front: "ひる", answers: ["siang"] },
  { front: "ばん", answers: ["malam"] },
  { front: "よる", answers: ["malam"] },
  { front: "おととい", answers: ["kemarin lusa", "dua hari yang lalu"] },
  { front: "きのう", answers: ["kemarin"] },
  { front: "きょう", answers: ["hari ini"] },
  { front: "あした", answers: ["besok"] },
  { front: "あさって", answers: ["lusa"] },
  { front: "けさ", answers: ["tadi pagi", "pagi ini"] },
  { front: "こんばん", answers: ["malam ini", "nanti malam"] },
  { front: "やすみ", answers: ["libur", "hari libur", "cuti", "istirahat"] },
  { front: "ひるやすみ", answers: ["istirahat siang"] },
  { front: "しけん", answers: ["ujian"] },
  { front: "かいぎ", answers: ["rapat"] },
  { front: "えいが", answers: ["film"] },
  { front: "まいあさ", answers: ["setiap pagi"] },
  { front: "まいばん", answers: ["setiap malam"] },
  { front: "まいにち", answers: ["setiap hari"] },
  { front: "げつようび", answers: ["hari Senin", "senin"] },
  { front: "かようび", answers: ["hari Selasa", "selasa"] },
  { front: "すいようび", answers: ["hari Rabu", "rabu"] },
  { front: "もくようび", answers: ["hari Kamis", "kamis"] },
  { front: "きんようび", answers: ["hari Jumat", "jumat"] },
  { front: "どようび", answers: ["hari Sabtu", "sabtu"] },
  { front: "にちようび", answers: ["hari Minggu", "minggu"] },
  { front: "なんようび", answers: ["hari apa"] },
  { front: "~から", answers: ["dari ~"] },
  { front: "~まで", answers: ["sampai ~"] },
  { front: "~と~", answers: ["~ dan ~"] },
  { front: "たいへんですね", answers: ["berat juga ya", "wah, susah ya", "o, berat ya"] },
  { front: "ばんごう", answers: ["nomor"] },
  { front: "なんばん", answers: ["nomor berapa"] },
  { front: "どちら", answers: ["di situ"] },
  { front: "ニューヨーク", answers: ["new york"] },
  { front: "ペキン", answers: ["beijing"] },
  { front: "ロサンゼルス", answers: ["los angeles"] },
  { front: "ロンドン", answers: ["london"] },
  { front: "けいさつしょ", answers: ["kantor polisi"] },
  { front: "しょうぼうしょ", answers: ["kantor pemadam kebakaran", "pemadam kebakaran"] },
  { front: "じほう", answers: ["pemberitahuan waktu"] },
  { front: "てんきよほう", answers: ["ramalan cuaca"] },
  { front: "でんわばんごうあんない", answers: ["petunjuk nomor telepon"] },
  { front: "いきます", answers: ["pergi"] },
  { front: "きます", answers: ["datang"] },
  { front: "かえります", answers: ["pulang"] },
  { front: "がっこう", answers: ["sekolah"] },
  { front: "スーパー", answers: ["swalayan", "pasar swalayan"] },
  { front: "えき", answers: ["stasiun"] },
  { front: "ひこうき", answers: ["pesawat terbang"] },
  { front: "ふね", answers: ["kapal laut", "kapal"] },
  { front: "でんしゃ", answers: ["kereta rel listrik", "kereta listrik"] },
  { front: "ちかてつ", answers: ["kereta bawah tanah"] },
  { front: "しんかんせん", answers: ["shinkansen"] },
  { front: "バス", answers: ["bus"] },
  { front: "タクシー", answers: ["taksi"] },
  { front: "じてんしゃ", answers: ["sepeda"] },
  { front: "あるいて", answers: ["berjalan kaki"] },
  { front: "ひと", answers: ["orang"] },
  { front: "ともだち", answers: ["teman"] },
  { front: "かれ", answers: ["dia laki-laki"] },
  { front: "かのじょ", answers: ["dia perempuan"] },
  { front: "かぞく", answers: ["keluarga"] },
  { front: "ひとりで", answers: ["sendirian", "dengan sendiri"] },
  { front: "せんしゅう", answers: ["minggu lalu"] },
  { front: "こんしゅう", answers: ["minggu ini"] },
  { front: "らいしゅう", answers: ["minggu depan"] },
  { front: "せんげつ", answers: ["bulan lalu"] },
  { front: "こんげつ", answers: ["bulan ini"] },
  { front: "らいげつ", answers: ["bulan depan"] },
  { front: "きょねん", answers: ["tahun lalu"] },
  { front: "ことし", answers: ["tahun ini"] },
  { front: "らいねん", answers: ["tahun depan"] },
  { front: "~ねん", answers: ["tahun ~"] },
  { front: "なんねん", answers: ["tahun berapa"] },
  { front: "~がつ", answers: ["bulan ~"] },
  { front: "なんがつ", answers: ["bulan apa"] },
  { front: "ついたち", answers: ["tanggal satu", "tanggal 1"] },
  { front: "ふつか", answers: ["tanggal dua"] },
  { front: "みっか", answers: ["tanggal tiga"] },
  { front: "よっか", answers: ["tanggal empat"] },
  { front: "いつか", answers: ["tanggal lima"] },
  { front: "むいか", answers: ["tanggal enam"] },
  { front: "なのか", answers: ["tanggal tujuh"] },
  { front: "ようか", answers: ["tanggal delapan"] },
  { front: "ここのか", answers: ["tanggal sembilan"] },
  { front: "じゅうよっか", answers: ["tanggal empat belas"] },
  { front: "はつか", answers: ["tanggal dua puluh"] },
  { front: "にじゅうよっか", answers: ["tanggal dua puluh empat", "tanggal 24"] },
  { front: "~にち", answers: ["tanggal ~", "~ hari"] },
  { front: "なんにち", answers: ["tanggal berapa", "berapa hari"] },
  { front: "いつ", answers: ["kapan"] },
  { front: "たんじょうび", answers: ["ulang tahun", "hari ulang tahun"] },
  { front: "そうですね", answers: ["ya betul", "ya begitulah"] },
  { front: "どういたしまして", answers: ["sama sama"] },
  { front: "~ばんせん", answers: ["peron nomor ~"] },
  { front: "つぎの", answers: ["yang berikutnya"] },
  { front: "ふつう", answers: ["biasa"] },
  { front: "きゅうこう", answers: ["ekspres"] },
  { front: "とっきゅう", answers: ["super ekspres", "ekspres super"] },
  { front: "がんじつ", answers: ["tahun baru"] },
  { front: "せいじんのひ", answers: ["hari perayaan menjadi dewasa", "hari kedewasaan"] },
  { front: "けんこくきねんのひ", answers: ["hari pembangunan nasional", "hari peringatan berdirinya negara"] },
  { front: "てんのうたんじょうび", answers: ["hari ulang tahun kaisar"] },
  { front: "しゅんぶんのひ", answers: ["hari equinox musim semi"] },
  { front: "しょうわのひ", answers: ["hari showa"] },
  { front: "けんぽうきねんび", answers: ["hari peringatan konstitusi"] },
  { front: "みどりのひ", answers: ["hari penghijauan"] },
  { front: "こどものひ", answers: ["hari anak"] },
  { front: "うみのひ", answers: ["hari bahari", "hari laut"] },
  { front: "やまのひ", answers: ["hari gunung"] },
  { front: "けいろうのひ", answers: ["hari hormat kepada orang tua"] },
  { front: "しゅうぶんのひ", answers: ["hari equinox musim gugur"] },
  { front: "スポーツのひ", answers: ["hari olahraga"] },
  { front: "ぶんかのひ", answers: ["hari kebudayaan"] },
  { front: "きんろうかんしゃのひ", answers: ["hari bersyukur untuk pekerjaan"] },
  { front: "たべます", answers: ["makan"] },
  { front: "のみます", answers: ["minum"] },
  { front: "すいます", answers: ["menghisap", "merokok"] },
  { front: "みます", answers: ["melihat", "menonton"] },
  { front: "ききます", answers: ["mendengar"] },
  { front: "よみます", answers: ["membaca"] },
  { front: "かきます", answers: ["menulis", "menggambar"] },
  { front: "かいます", answers: ["membeli"] },
  { front: "とります", answers: ["mengambil foto"] },
  { front: "します", answers: ["mengerjakan", "melakukan", "berbuat"] },
  { front: "あいます", answers: ["bertemu"] },
  { front: "ごはん", answers: ["nasi"] },
  { front: "あさごはん", answers: ["sarapan", "makan pagi"] },
  { front: "ひるごはん", answers: ["makan siang"] },
  { front: "ばんごはん", answers: ["makan malam"] },
  { front: "パン", answers: ["roti"] },
  { front: "たまご", answers: ["telur"] },
  { front: "にく", answers: ["daging"] },
  { front: "やさい", answers: ["sayur", "sayuran"] },
  { front: "くだもの", answers: ["buah buahan", "buah-buahan"] },
  { front: "みず", answers: ["air"] },
  { front: "おちゃ", answers: ["teh", "teh Jepang", "teh hijau"] },
  { front: "こうちゃ", answers: ["teh"] },
  { front: "ぎゅうにゅう", answers: ["susu"] },
  { front: "ミルク", answers: ["susu"] },
  { front: "ジュース", answers: ["jus", "sari buah"] },
  { front: "ビール", answers: ["bir"] },
  { front: "おさけ", answers: ["minuman keras", "miras"] },
  { front: "タバコ", answers: ["rokok"] },
  { front: "てがみ", answers: ["surat"] },
  { front: "レポート", answers: ["laporan"] },
  { front: "しゃしん", answers: ["foto"] },
  { front: "ビデオ", answers: ["kaset video", "VHS", "video"] },
  { front: "みせ", answers: ["toko"] },
  { front: "にわ", answers: ["halaman"] },
  { front: "しゅくだい", answers: ["PR", "pekerjaan rumah"] },
  { front: "テニス", answers: ["tenis"] },
  { front: "サッカー", answers: ["sepak bola"] },
  { front: "おはなみ", answers: ["menikmati bunga sakura"] },
  { front: "なに", answers: ["apa"] },
  { front: "いっしょに", answers: ["bersama-sama"] },
  { front: "ちょっと", answers: ["sebentar", "sedikit"] },
  { front: "いつも", answers: ["selalu"] },
  { front: "ときどき", answers: ["kadang-kadang"] },
  { front: "それから", answers: ["setelah itu", "kemudian"] },
  { front: "ええ", answers: ["ya"] },
  { front: "いいですね", answers: ["bagus ya", "baik ya"] },
  { front: "わかりました", answers: ["mengerti", "baik"] },
  { front: "なんですか", answers: ["apa"] },
  { front: "じゃ、またあした", answers: ["ok, sampai jumpa besok", "sampai jumpa besok"] },
  { front: "メキシコ", answers: ["meksiko"] },
  { front: "たべもの", answers: ["makanan"] },
  { front: "きゅうり", answers: ["ketimun"] },
  { front: "トマト", answers: ["tomat"] },
  { front: "なす", answers: ["terong"] },
  { front: "まめ", answers: ["kacang", "kacang-kacangan"] },
  { front: "キャベツ", answers: ["kol"] },
  { front: "ねぎ", answers: ["daun bawang"] },
  { front: "はくさい", answers: ["sawi"] },
  { front: "ほうれんそう", answers: ["bayam"] },
  { front: "レタス", answers: ["selada"] },
  { front: "じゃがいも", answers: ["kentang"] },
  { front: "だいこん", answers: ["lobak"] },
  { front: "たまねぎ", answers: ["bawang"] },
  { front: "にんじん", answers: ["wortel"] },
  { front: "いちご", answers: ["stroberi"] },
  { front: "もも", answers: ["peach", "buah persik"] },
  { front: "すいか", answers: ["semangka"] },
  { front: "ぶどう", answers: ["anggur"] },
  { front: "なし", answers: ["pir"] },
  { front: "かき", answers: ["kesemek"] },
  { front: "みかん", answers: ["jeruk"] },
  { front: "りんご", answers: ["apel"] },
  { front: "バナナ", answers: ["pisang"] },
  { front: "こめ", answers: ["beras"] },
  { front: "ぎゅうにく", answers: ["daging sapi"] },
  { front: "とりにく", answers: ["daging ayam"] },
  { front: "ぶたにく", answers: ["daging babi"] },
  { front: "ソーセージ", answers: ["sosis"] },
  { front: "ハム", answers: ["ham"] },
  { front: "あじ", answers: ["ikan mackerel", "ikan aji"] },
  { front: "いわし", answers: ["sarden", "ikan sarden"] },
  { front: "さば", answers: ["ikan kembung", "saba"] },
  { front: "さんま", answers: ["ikan sauri pasifik", "ikan samma"] },
  { front: "さけ", answers: ["ikan salmon", "salmon"] },
  { front: "まぐろ", answers: ["ikan tuna", "tuna"] },
  { front: "たい", answers: ["ikan kakap", "kakap"] },
  { front: "たら", answers: ["ikan kod", "kod"] },
  { front: "えび", answers: ["udang"] },
  { front: "かに", answers: ["kepiting"] },
  { front: "いか", answers: ["cumi-cumi"] },
  { front: "たこ", answers: ["gurita"] },
  { front: "かい", answers: ["kerang"] },
  { front: "きります", answers: ["memotong", "menggunting"] },
  { front: "おくります", answers: ["mengirim"] },
  { front: "あげます", answers: ["memberikan"] },
  { front: "もらいます", answers: ["mendapatkan", "menerima"] },
  { front: "かします", answers: ["meminjamkan", "menyewakan"] },
  { front: "かります", answers: ["meminjam", "menyewa"] },
  { front: "おしえます", answers: ["mengajar"] },
  { front: "ならいます", answers: ["belajar", "belajar dari"] },
  { front: "かけます", answers: ["menelepon"] },
  { front: "て", answers: ["tangan"] },
  { front: "はし", answers: ["sumpit"] },
  { front: "スプーン", answers: ["sendok"] },
  { front: "ナイフ", answers: ["pisau"] },
  { front: "フォーク", answers: ["garpu"] },
  { front: "はさみ", answers: ["gunting"] },
  { front: "パソコン", answers: ["komputer", "PC"] },
  { front: "ケータイ", answers: ["HP", "handphone"] },
  { front: "メール", answers: ["email"] },
  { front: "ねんがじょう", answers: ["kartu tahun baru"] },
  { front: "パンチ", answers: ["pelubang kertas"] },
  { front: "ホチキス", answers: ["stapler"] },
  { front: "セロテープ", answers: ["selotip"] },
  { front: "けしごむ", answers: ["penghapus karet"] },
  { front: "かみ", answers: ["kertas"] },
  { front: "はな", answers: ["bunga"] },
  { front: "シャツ", answers: ["kemeja"] },
  { front: "プレゼント", answers: ["hadiah", "kado"] },
  { front: "にもつ", answers: ["barang"] },
  { front: "おかね", answers: ["uang"] },
  { front: "きっぷ", answers: ["karcis"] },
  { front: "クリスマス", answers: ["natal"] },
  { front: "ちち", answers: ["ayah", "bapak"] },
  { front: "はは", answers: ["ibu"] },
  { front: "おとうさん", answers: ["ayah", "bapak"] },
  { front: "おかあさん", answers: ["ibu"] },
  { front: "もう", answers: ["sudah"] },
  { front: "まだ", answers: ["belum"] },
  { front: "これから", answers: ["mulai sekarang"] },
  { front: "すてきですね", answers: ["bagus ya", "indah ya"] },
  { front: "いらっしゃい", answers: ["selamat datang"] },
  { front: "どうぞ おあがりください", answers: ["silahkan masuk"] },
  { front: "しつれいします", answers: ["permisi"] },
  { front: "~わ いかがですか", answers: ["bagaimana ~"] },
  { front: "いただきます", answers: ["selamat makan"] },
  { front: "ごちそうさまでした", answers: ["terimakasih atas hidangannya"] },
  { front: "そぼ", answers: ["nenek"] },
  { front: "そふ", answers: ["kakek"] },
  { front: "そふぼ", answers: ["kakek nenek"] },
  { front: "りょうしん", answers: ["orang tua"] },
  { front: "いもうと", answers: ["adik perempuan"] },
  { front: "おとうと", answers: ["adik laki-laki"] },
  { front: "あね", answers: ["kakak perempuan"] },
  { front: "あに", answers: ["kakak laki-laki"] },
  { front: "きょうだい", answers: ["saudara"] },
  { front: "つま", answers: ["istri"] },
  { front: "おっと", answers: ["suami"] },
  { front: "ふうふ", answers: ["pasangan suami istri"] },
  { front: "むすめ", answers: ["anak perempuan"] },
  { front: "むすこ", answers: ["anak laki-laki"] },
  { front: "こども", answers: ["anak"] },
  { front: "おばあさん", answers: ["nenek"] },
  { front: "おじいさん", answers: ["kakek"] },
  { front: "ごりょうしん", answers: ["orang tua"] },
  { front: "いもうとさん", answers: ["adik perempuan"] },
  { front: "おとうとさん", answers: ["adik laki-laki"] },
  { front: "おねえさん", answers: ["kakak perempuan"] },
  { front: "おにいさん", answers: ["kakak laki-laki"] },
  { front: "ごきょうだい", answers: ["saudara"] },
  { front: "おくさん", answers: ["istri"] },
  { front: "ごしゅじん", answers: ["suami"] },
  { front: "ごふうふ", answers: ["pasangan suami istri"] },
  { front: "むすめさん", answers: ["anak perempuan"] },
  { front: "むすこさん", answers: ["anak laki-laki"] },
  { front: "おこさん", answers: ["anak"] },
  { front: "ハンサム", answers: ["tampan", "gagah", "ganteng"] },
  { front: "きれい", answers: ["cantik", "bersih"] },
  { front: "しずか", answers: ["sunyi", "tenang"] },
  { front: "にぎやか", answers: ["ramai"] },
  { front: "ゆうめい", answers: ["terkenal"] },
  { front: "しんせつ", answers: ["baik hati", "baik"] },
  { front: "げんき", answers: ["sehat walafiat", "sehat"] },
  { front: "ひま", answers: ["senggang"] },
  { front: "べんり", answers: ["praktis"] },
  { front: "すてき", answers: ["bagus"] },
  { front: "おおきい", answers: ["besar"] },
  { front: "ちいさい", answers: ["kecil"] },
  { front: "あたらしい", answers: ["baru"] },
  { front: "ふるい", answers: ["lama"] },
  { front: "いい", answers: ["baik", "bagus"] },
  { front: "よい", answers: ["baik", "bagus"] },
  { front: "わるい", answers: ["buruk", "jelek"] },
  { front: "あつい", answers: ["panas"] },
  { front: "さむい", answers: ["dingin"] },
  { front: "つめたい", answers: ["dingin"] },
  { front: "むずかしい", answers: ["susah", "sulit"] },
  { front: "やさしい", answers: ["mudah", "gampang"] },
  { front: "たかい", answers: ["mahal", "tinggi"] },
  { front: "やすい", answers: ["murah"] },
  { front: "ひくい", answers: ["rendah"] },
  { front: "おもしろい", answers: ["menarik"] },
  { front: "おいしい", answers: ["enak"] },
  { front: "いそがしい", answers: ["sibuk"] },
  { front: "たのしい", answers: ["senang"] },
  { front: "しろい", answers: ["putih"] },
  { front: "くろい", answers: ["hitam"] },
  { front: "あかい", answers: ["merah"] },
  { front: "あおい", answers: ["biru"] },
  { front: "さくら", answers: ["sakura"] },
  { front: "やま", answers: ["gunung"] },
  { front: "まち", answers: ["kota"] },
  { front: "ところ", answers: ["tempat"] },
  { front: "りょう", answers: ["asrama"] },
  { front: "レストラン", answers: ["restoran"] },
  { front: "せいかつ", answers: ["kehidupan"] },
  { front: "おしごと", answers: ["pekerjaan"] },
  { front: "どう", answers: ["bagaimana"] },
  { front: "どんな", answers: ["yang bagaimana"] },
  { front: "とても", answers: ["sangat", "~ sekali"] },
  { front: "あまり", answers: ["kurang begitu ~", "tidak begitu ~"] },
  { front: "そして", answers: ["kemudian", "dan", "lalu"] },
  { front: "~が、~", answers: ["~, tetapi ~"] },
  { front: "おげんきですか", answers: ["apa kabar"] },
  { front: "そうですね", answers: ["bagaimana ya"] },
  { front: "もう いっぱい いかがですか", answers: ["mau tambah secangkir lagi"] },
  { front: "いいえ、けっこうです", answers: ["tidak, sudah cukup"] },
  { front: "もう ~ ですね", answers: ["sudah ~ ya"] },
  { front: "そろそろ しつれいします", answers: ["maaf saya mau pamit dulu"] },
  { front: "いいえ", answers: ["sama sama"] },
  { front: "また いらっしゃってください", answers: ["silahkan datang lagi"] },
  { front: "シャンハイ", answers: ["shanghai"] },
  { front: "わかります", answers: ["mengerti"] },
  { front: "あります", answers: ["ada", "mempunyai"] },
  { front: "すき", answers: ["suka", "gemar"] },
  { front: "きらい", answers: ["tidak suka"] },
  { front: "じょうず", answers: ["pintar", "pandai"] },
  { front: "へた", answers: ["tidak pintar", "tidak pandai"] },
  { front: "のみもの", answers: ["minuman"] },
  { front: "りょうり", answers: ["masakan"] },
  { front: "スポーツ", answers: ["olahraga"] },
  { front: "やきゅう", answers: ["baseball"] },
  { front: "ダンス", answers: ["dansa"] },
  { front: "りょこう", answers: ["tamasya"] },
  { front: "おんがく", answers: ["musik"] },
  { front: "うた", answers: ["lagu"] },
  { front: "クラシック", answers: ["klasik"] },
  { front: "ジャズ", answers: ["jaz", "jazz"] },
  { front: "コンサート", answers: ["konser"] },
  { front: "カラオケ", answers: ["karaoke"] },
  { front: "かぶき", answers: ["kabuki", "drama tradisional Jepang"] },
  { front: "え", answers: ["gambar"] },
  { front: "じ", answers: ["huruf"] },
  { front: "かんじ", answers: ["kanji"] },
  { front: "ひらがな", answers: ["hiragana"] },
  { front: "カタカナ", answers: ["katakana"] },
  { front: "ローマじ", answers: ["romaji"] },
  { front: "こまかい おかね", answers: ["uang kecil", "uang receh", "receh"] },
  { front: "チケット", answers: ["tiket"] },
  { front: "じかん", answers: ["jam", "waktu"] },
  { front: "ようじ", answers: ["urusan"] },
  { front: "やくそく", answers: ["janji"] },
  { front: "アルバイト", answers: ["kerja paruh waktu", "part time job"] },
  { front: "よく", answers: ["dengan baik"] },
  { front: "だいたい", answers: ["kira kira"] },
  { front: "たくさん", answers: ["banyak"] },
  { front: "すこし", answers: ["sedikit"] },
  { front: "ぜんぜん", answers: ["sama sekali"] },
  { front: "はやく", answers: ["cepat", "dengan cepat"] },
  { front: "~から", answers: ["karena ~", "sebab ~"] },
  { front: "どうして", answers: ["kenapa"] },
  { front: "かして ください", answers: ["tolong pinjamkan"] },
  { front: "いいですよ", answers: ["boleh"] },
  { front: "ざんねんです", answers: ["sayang sekali"] },
  { front: "ああ", answers: ["ah"] },
  { front: "いっしょに いかがですか", answers: ["bagaimana kalau bersama-sama"] },
  { front: "だめですか", answers: ["tidak bisa ya", "tidak boleh ya"] },
  { front: "また こんど おねがいします", answers: ["maaf lain kali saja"] },
  { front: "ポップス", answers: ["pop"] },
  { front: "ロック", answers: ["rock"] },
  { front: "ラテン", answers: ["musik latin", "latin"] },
  { front: "みんよう", answers: ["musik rakyat", "nyanyian daerah"] },
  { front: "えんか", answers: ["lagu tradisional"] },
  { front: "ミュージカル", answers: ["drama musikal"] },
  { front: "オペラ", answers: ["opera"] },
  { front: "SF", answers: ["fiksi ilmiah", "scifi"] },
  { front: "ホラー", answers: ["horor"] },
  { front: "アニメ", answers: ["kartun", "animasi", "anime"] },
  { front: "ドキュメンタリー", answers: ["dokumentasi"] },
  { front: "れんあい", answers: ["percintaan"] },
  { front: "ミステリー", answers: ["misteri"] },
  { front: "ぶんげい", answers: ["kesusastraan"] },
  { front: "せんそう", answers: ["peperangan"] },
  { front: "アクション", answers: ["action", "aksi"] },
  { front: "きげき", answers: ["komedi"] },
  { front: "ソフトボール", answers: ["softball"] },
  { front: "サッカー", answers: ["sepak bola"] },
  { front: "ラグビー", answers: ["rugby"] },
  { front: "バレーボール", answers: ["voli"] },
  { front: "バスケットボール", answers: ["basket"] },
  { front: "ボウリング", answers: ["bowling"] },
  { front: "スキー", answers: ["ski"] },
  { front: "スケート", answers: ["skate"] },
  { front: "たっきゅう", answers: ["ping-pong", "pingpong", "ping pong"] },
  { front: "ピンポン", answers: ["ping-pong", "pingpong", "ping pong"] },
  { front: "じゅうどう", answers: ["judo"] },
  { front: "けんどう", answers: ["kendo"] },
  { front: "すいえい", answers: ["renang"] },
  { front: "います", answers: ["ada"] },
  { front: "いろいろ", answers: ["berbagai"] },
  { front: "おとこのひと", answers: ["orang laki-laki"] },
  { front: "おんなのひと", answers: ["orang perempuan"] },
  { front: "おとこのこ", answers: ["anak laki-laki"] },
  { front: "おんなのこ", answers: ["anak perempuan"] },
  { front: "いぬ", answers: ["anjing"] },
  { front: "ねこ", answers: ["kucing"] },
  { front: "パンダ", answers: ["panda"] },
  { front: "ぞう", answers: ["gajah"] },
  { front: "き", answers: ["pohon"] },
  { front: "もの", answers: ["barang"] },
  { front: "でんち", answers: ["baterai"] },
  { front: "はこ", answers: ["kotak"] },
  { front: "スイッチ", answers: ["tombol", "saklar", "sakelar"] },
  { front: "れいぞうこ", answers: ["kulkas", "lemari es"] },
  { front: "テーブル", answers: ["meja", "meja makan"] },
  { front: "ベッド", answers: ["kasur", "tempat tidur"] },
  { front: "たな", answers: ["lemari", "almari"] },
  { front: "ドア", answers: ["pintu"] },
  { front: "まど", answers: ["jendela"] },
  { front: "ポスト", answers: ["kotak surat", "kotak pos"] },
  { front: "ビル", answers: ["gedung"] },
  { front: "ATM", answers: ["ATM", "anjungan tunai mandiri"] },
  { front: "コンビニ", answers: ["toko", "toko 24 jam"] },
  { front: "こうえん", answers: ["taman"] },
  { front: "きっさてん", answers: ["kafe", "coffee shop"] },
  { front: "~や", answers: ["toko ~"] },
  { front: "のりば", answers: ["tempat naik"] },
  { front: "けん", answers: ["prefektur"] },
  { front: "うえ", answers: ["atas"] },
  { front: "した", answers: ["bawah"] },
  { front: "まえ", answers: ["depan", "muka"] },
  { front: "うしろ", answers: ["belakang"] },
  { front: "みぎ", answers: ["kanan"] },
  { front: "ひだり", answers: ["kiri"] },
  { front: "なか", answers: ["dalam"] },
  { front: "そと", answers: ["luar"] },
  { front: "となり", answers: ["sebelah"] },
  { front: "ちかく", answers: ["dekat"] },
  { front: "あいだ", answers: ["antara"] },
  { front: "~や", answers: ["~ dan"] },
  { front: "~など", answers: ["~ dan lain-lain"] },
  { front: "どうも すみません", answers: ["terimakasih banyak"] },
  { front: "ナンプラー", answers: ["kecap ikan"] },
  { front: "コーナー", answers: ["tempat penjualan", "bagian penjualan"] },
  { front: "いちばん した", answers: ["paling bawah"] },
  { front: "とうきょう ディズニーランド", answers: ["Tokyo Disneyland"] },
  { front: "げんかん", answers: ["pintu masuk"] },
  { front: "ふろば", answers: ["kamar mandi"] },
  { front: "せんめんじょ", answers: ["tempat cuci tangan"] },
  { front: "だいどころ", answers: ["dapur"] },
  { front: "いま", answers: ["ruang tamu"] },
  { front: "しんしつ", answers: ["kamar tidur"] },
  { front: "ろうか", answers: ["koridor"] },
  { front: "ベランダ", answers: ["teras"] },
].map(c => ({ ...c, type: "vocab" }));

export { VOCAB_KANA };
