// vocab_data.js
// Japanese → Bahasa Indonesia vocabulary flashcard data.
// Each entry: { front, answers[], type, label }
// answers[] accepts multiple correct translations (case-insensitive).

// answers[] supports multiple accepted translations per card.
// Add more entries following the same shape.
const VOCAB = [
  { front: "わたし", answers: ["saya", "aku"], label: "artinya" },
  { front: "あなた", answers: ["anda"], label: "artinya" },
  { front: "あのひと", answers: ["orang itu"], label: "artinya" },
  { front: "あのかた", answers: ["orang itu"], label: "artinya" },
  { front: "~さん", answers: ["saudara ~"], label: "artinya" },
  { front: "~ちゃん", answers: ["anak ~"], label: "artinya" },
  { front: "~じん", answers: ["orang ~"], label: "artinya" },
  { front: "せんせい", answers: ["guru"], label: "artinya" },
  { front: "きょうし", answers: ["guru"], label: "artinya" },
  { front: "ごくせい", answers: ["mahasiswa"], label: "artinya" },
  { front: "かいしゃいん", answers: ["karyawan"], label: "artinya" },
  { front: "~のしゃいん", answers: ["karyawan ~"], label: "artinya" },
  { front: "ぎんこういん", answers: ["pegawai bank"], label: "artinya" },
  { front: "いしゃ", answers: ["dokter"], label: "artinya" },
  { front: "けんきゅうしゃ", answers: ["peneliti"], label: "artinya" },
  { front: "だいがく", answers: ["universitas"], label: "artinya" },
  { front: "びょういん", answers: ["rumah sakit"], label: "artinya" },
  { front: "だれ", answers: ["siapa"], label: "artinya" },
  { front: "どなた", answers: ["siapa"], label: "artinya" },
  { front: "~さい", answers: ["~ tahun"], label: "artinya" },
  { front: "なんさい", answers: ["umur berapa"], label: "artinya" },
  { front: "おいくつ", answers: ["umur berapa"], label: "artinya" },
  { front: "はい", answers: ["iya"], label: "artinya" },
  { front: "いいえ", answers: ["tidak"], label: "artinya" },
  { front: "はじめまして", answers: ["perkenalkan"], label: "artinya" },
  { front: "~からきました", answers: ["datang dari ~"], label: "artinya" },
  { front: "どうぞよろしくおねがいします", answers: ["salam kenal"], label: "artinya" },
  { front: "しつれいですか", answers: ["permisi"], label: "artinya" },
  { front: "おなまえわ", answers: ["siapa namanya?"], label: "artinya" },
  { front: "こちらわ ~さん です", answers: ["ini saudara ~"], label: "artinya" },
  { front: "アメリカ", answers: ["amerika"], label: "artinya" },
  { front: "イギリス", answers: ["inggris"], label: "artinya" },
  { front: "インド", answers: ["india"], label: "artinya" },
  { front: "インドネシア", answers: ["indonesia"], label: "artinya" },
  { front: "カンコク", answers: ["korea selatan"], label: "artinya" },
  { front: "タイ", answers: ["thailand"], label: "artinya" },
  { front: "チュウゴク", answers: ["cina"], label: "artinya" },
  { front: "ドイツ", answers: ["jerman"], label: "artinya" },
  { front: "ニホン", answers: ["jepang"], label: "artinya" },
  { front: "ブラジル", answers: ["brazil"], label: "artinya" },
  { front: "これ", answers: ["ini"], label: "artinya" },
  { front: "それ", answers: ["itu"], label: "artinya" },
  { front: "あれ", answers: ["itu"], label: "artinya" },
  { front: "この ~", answers: ["~ ini"], label: "artinya" },
  { front: "その ~", answers: ["~ itu"], label: "artinya" },
  { front: "あの ~", answers: ["~ itu"], label: "artinya" },
  { front: "ほん", answers: ["buku"], label: "artinya" },
  { front: "じしょ", answers: ["kamus"], label: "artinya" },
  { front: "ざっし", answers: ["majalah"], label: "artinya" },
  { front: "しんぶん", answers: ["koran"], label: "artinya" },
  { front: "ノート", answers: ["buku tulis"], label: "artinya" },
  { front: "てちょう", answers: ["buku agenda"], label: "artinya" },
  { front: "めいし", answers: ["kartu nama"], label: "artinya" },
  { front: "カード", answers: ["kartu"], label: "artinya" },
  { front: "えんぴつ", answers: ["pensil"], label: "artinya" },
  { front: "ボールペン", answers: ["bolpoin"], label: "artinya" },
  { front: "シャープペンシル", answers: ["pensil mekanik"], label: "artinya" },
  { front: "かぎ", answers: ["kunci"], label: "artinya" },
  { front: "とけい", answers: ["jam"], label: "artinya" },
  { front: "かさ", answers: ["payung"], label: "artinya" },
  { front: "かばん", answers: ["tas"], label: "artinya" },
  { front: "CD", answers: ["CD"], label: "artinya" },
  { front: "テレビ", answers: ["TV"], label: "artinya" },
  { front: "ラジオ", answers: ["radio"], label: "artinya" },
  { front: "カメラ", answers: ["kamera"], label: "artinya" },
  { front: "コンピューター", answers: ["komputer"], label: "artinya" },
  { front: "くるま", answers: ["mobil"], label: "artinya" },
  { front: "いす", answers: ["kursi"], label: "artinya" },
  { front: "つくえ", answers: ["meja"], label: "artinya" },
  { front: "チョコレート", answers: ["coklat"], label: "artinya" },
  { front: "コーヒー", answers: ["kopi"], label: "artinya" },
  { front: "みやげ", answers: ["oleh-oleh"], label: "artinya" },
  { front: "くつ", answers: ["sepatu"], label: "artinya" },
  { front: "ネクタイ", answers: ["dasi"], label: "artinya" },
  { front: "ワイン", answers: ["anggur"], label: "artinya" },
  { front: "えいご", answers: ["bahasa Inggris"], label: "artinya" },
  { front: "にほんご", answers: ["bahasa Jepang"], label: "artinya" },
  { front: "~ご", answers: ["bahasa ~"], label: "artinya" },
  { front: "ここ", answers: ["sini"], label: "artinya" },
  { front: "そこ", answers: ["situ"], label: "artinya" },
  { front: "あそこ", answers: ["sana"], label: "artinya" },
  { front: "どこ", answers: ["dimana"], label: "artinya" },
  { front: "こちら", answers: ["sini"], label: "artinya" },
  { front: "そちら", answers: ["situ"], label: "artinya" },
  { front: "あちら", answers: ["sana"], label: "artinya" },
  { front: "どちら", answers: ["dimana"], label: "artinya" },
  { front: "きょうしつ", answers: ["ruang kelas"], label: "artinya" },
  { front: "しょくどう", answers: ["ruang makan"], label: "artinya" },
  { front: "じむしょ", answers: ["kantor"], label: "artinya" },
  { front: "かいぎしつ", answers: ["ruang rapat"], label: "artinya" },
  { front: "うけつけ", answers: ["meja informasi"], label: "artinya" },
  { front: "ロビー", answers: ["lobi"], label: "artinya" },
  { front: "へや", answers: ["kamar"], label: "artinya" },
  { front: "トイレ", answers: ["toilet"], label: "artinya" },
  { front: "おてあらい", answers: ["toilet"], label: "artinya" },
  { front: "かいだん", answers: ["tangga"], label: "artinya" },
  { front: "エレベーター", answers: ["lift"], label: "artinya" },
  { front: "エスカレーター", answers: ["eskalator"], label: "artinya" },
  { front: "じどうはんばいき", answers: ["mesin jual otomatis"], label: "artinya" },
  { front: "でんわ", answers: ["telepon"], label: "artinya" },
  { front: "おくに", answers: ["negara"], label: "artinya" },
  { front: "かいしゃ", answers: ["perusahaan"], label: "artinya" },
  { front: "うち", answers: ["rumah"], label: "artinya" },
  { front: "うりば", answers: ["toko"], label: "artinya" },
  { front: "ちか", answers: ["basement"], label: "artinya" },
  { front: "~かい", answers: ["lantai ~"], label: "artinya" },
  { front: "~がい", answers: ["lantai ~"], label: "artinya" },
  { front: "なんがい", answers: ["lantai berapa"], label: "artinya" },
  { front: "~えん", answers: ["~ yen"], label: "artinya" },
  { front: "いくら", answers: ["berapa"], label: "artinya" },
  { front: "ひゃく", answers: ["ratus"], label: "artinya" },
  { front: "せん", answers: ["ribu"], label: "artinya" },
  { front: "まん", answers: ["puluh ribu"], label: "artinya" },
  { front: "なん", answers: ["apa"], label: "artinya" },
  { front: "そう", answers: ["begitu"], label: "artinya" },
  { front: "あのう", answers: ["eee..."], label: "artinya" },
  { front: "どうぞ", answers: ["silahkan"], label: "artinya" },
  { front: "すみません", answers: ["permisi"], label: "artinya" },
  { front: "どうも", answers: ["terimakasih"], label: "artinya" },
  { front: "いらっしゃいませ", answers: ["selamat datang"], label: "artinya" },
  { front: "じゃ", answers: ["kalau begitu"], label: "artinya" },
  { front: "~を みせて ください", answers: ["tolong perlihatkan ~"], label: "artinya" },
  { front: "~を ください", answers: ["minta ~"], label: "artinya" },
  { front: "どうも ありがとう ございます", answers: ["terimakasih banyak"], label: "artinya" },
  { front: "そう ですか", answers: ["o begitu"], label: "artinya" },
  { front: "ちがいます", answers: ["bukan begitu"], label: "artinya" },
  { front: "これから おせわに なります", answers: ["mulai sekarang mohon bantuannya"], label: "artinya" },
  { front: "こちらこそ どうぞ よろしく おねがいします", answers: ["ya, sama-sama"], label: "artinya" },
  { front: "イタリア", answers: ["italia"], label: "artinya" },
  { front: "スイス", answers: ["swiss"], label: "artinya" },
  { front: "フランス", answers: ["perancis"], label: "artinya" },
  { front: "ジャカルタ", answers: ["jakarta"], label: "artinya" },
  { front: "バンコク", answers: ["bangkok"], label: "artinya" },
  { front: "ベルリン", answers: ["berlin"], label: "artinya" },
  { front: "おくじょう", answers: ["atap", "rooftop"], label: "artinya" },
  { front: "ゆうえんち", answers: ["tempat hiburan", "taman hiburan"], label: "artinya" },
  { front: "レストラン", answers: ["restoran"], label: "artinya" },
  { front: "もよおしものかいじょう", answers: ["tempat acara", "tempat pertunjukan"], label: "artinya" },
  { front: "めがね", answers: ["kacamata"], label: "artinya" },
  { front: "スポーツようひん", answers: ["perlengkapan olahraga"], label: "artinya" },
  { front: "りょこうようひん", answers: ["perlengkapan bepergian"], label: "artinya" },
  { front: "こどもふく", answers: ["pakaian anak"], label: "artinya" },
  { front: "おもちゃ", answers: ["mainan"], label: "artinya" },
  { front: "ぶんぼうぐ", answers: ["alat tulis"], label: "artinya" },
  { front: "かぐ", answers: ["mebel", "furnitur"], label: "artinya" },
  { front: "しょっき", answers: ["peralatan makan", "alat makan"], label: "artinya" },
  { front: "でんきせいひん", answers: ["peralatan elektronik", "barang elektronik"], label: "artinya" },
  { front: "しんしふく", answers: ["pakaian pria"], label: "artinya" },
  { front: "ふじんふく", answers: ["pakaian wanita"], label: "artinya" },
  { front: "くつ", answers: ["sepatu"], label: "artinya" },
  { front: "アクセサリー", answers: ["aksesoris", "perhiasan"], label: "artinya" },
  { front: "けしょうひん", answers: ["kosmetik"], label: "artinya" },
  { front: "しょくひん", answers: ["bahan makanan", "makanan"], label: "artinya" },
  { front: "ちゅうしゃじょう", answers: ["tempat parkir"], label: "artinya" },
  { front: "おきます", answers: ["bangun"], label: "artinya" },
  { front: "ねます", answers: ["tidur"], label: "artinya" },
  { front: "はたらきます", answers: ["bekerja"], label: "artinya" },
  { front: "やすみます", answers: ["libur", "istirahat", "beristirahat"], label: "artinya" },
  { front: "べんきょうします", answers: ["belajar"], label: "artinya" },
  { front: "おわります", answers: ["selesai", "berakhir"], label: "artinya" },
  { front: "デパート", answers: ["toserba", "department store"], label: "artinya" },
  { front: "ぎんこう", answers: ["bank"], label: "artinya" },
  { front: "ゆうびんきょく", answers: ["kantor pos"], label: "artinya" },
  { front: "としょかん", answers: ["perpustakaan"], label: "artinya" },
  { front: "びじゅつかん", answers: ["museum seni", "gedung kesenian"], label: "artinya" },
  { front: "いま", answers: ["sekarang"], label: "artinya" },
  { front: "~じ", answers: ["jam ~", "pukul ~"], label: "artinya" },
  { front: "~ふん", answers: ["~ menit"], label: "artinya" },
  { front: "~ぷん", answers: ["~ menit"], label: "artinya" },
  { front: "はん", answers: ["setengah"], label: "artinya" },
  { front: "なんじ", answers: ["jam berapa", "pukul berapa"], label: "artinya" },
  { front: "なんぷん", answers: ["menit berapa", "berapa menit"], label: "artinya" },
  { front: "ごぜん", answers: ["pagi", "AM"], label: "artinya" },
  { front: "ごご", answers: ["siang", "sore", "PM"], label: "artinya" },
  { front: "あさ", answers: ["pagi"], label: "artinya" },
  { front: "ひる", answers: ["siang"], label: "artinya" },
  { front: "ばん", answers: ["malam"], label: "artinya" },
  { front: "よる", answers: ["malam"], label: "artinya" },
  { front: "おととい", answers: ["kemarin lusa", "dua hari yang lalu"], label: "artinya" },
  { front: "きのう", answers: ["kemarin"], label: "artinya" },
  { front: "きょう", answers: ["hari ini"], label: "artinya" },
  { front: "あした", answers: ["besok"], label: "artinya" },
  { front: "あさって", answers: ["lusa"], label: "artinya" },
  { front: "けさ", answers: ["tadi pagi", "pagi ini"], label: "artinya" },
  { front: "こんばん", answers: ["malam ini", "nanti malam"], label: "artinya" },
  { front: "やすみ", answers: ["libur", "hari libur", "cuti", "istirahat"], label: "artinya" },
  { front: "ひるやすみ", answers: ["istirahat siang"], label: "artinya" },
  { front: "しけん", answers: ["ujian"], label: "artinya" },
  { front: "かいぎ", answers: ["rapat"], label: "artinya" },
  { front: "えいが", answers: ["film"], label: "artinya" },
  { front: "まいあさ", answers: ["setiap pagi"], label: "artinya" },
  { front: "まいばん", answers: ["setiap malam"], label: "artinya" },
  { front: "まいにち", answers: ["setiap hari"], label: "artinya" },
  { front: "げつようび", answers: ["hari Senin", "senin"], label: "artinya" },
  { front: "かようび", answers: ["hari Selasa", "selasa"], label: "artinya" },
  { front: "すいようび", answers: ["hari Rabu", "rabu"], label: "artinya" },
  { front: "もくようび", answers: ["hari Kamis", "kamis"], label: "artinya" },
  { front: "きんようび", answers: ["hari Jumat", "jumat"], label: "artinya" },
  { front: "どようび", answers: ["hari Sabtu", "sabtu"], label: "artinya" },
  { front: "にちようび", answers: ["hari Minggu", "minggu"], label: "artinya" },
  { front: "なんようび", answers: ["hari apa"], label: "artinya" },
  { front: "~から", answers: ["dari ~"], label: "artinya" },
  { front: "~まで", answers: ["sampai ~"], label: "artinya" },
  { front: "~と~", answers: ["~ dan ~"], label: "artinya" },
  { front: "たいへんですね", answers: ["berat juga ya", "wah, susah ya", "o, berat ya"], label: "artinya" },
  { front: "ばんごう", answers: ["nomor"], label: "artinya" },
  { front: "なんばん", answers: ["nomor berapa"], label: "artinya" },
  { front: "どちら", answers: ["di situ"], label: "artinya" },
  { front: "ニューヨーク", answers: ["new york"], label: "artinya" },
  { front: "ペキン", answers: ["beijing"], label: "artinya" },
  { front: "ロサンゼルス", answers: ["los angeles"], label: "artinya" },
  { front: "ロンドン", answers: ["london"], label: "artinya" },
  { front: "けいさつしょ", answers: ["kantor polisi"], label: "artinya" },
  { front: "しょうぼうしょ", answers: ["kantor pemadam kebakaran", "pemadam kebakaran"], label: "artinya" },
  { front: "じほう", answers: ["pemberitahuan waktu"], label: "artinya" },
  { front: "てんきよほう", answers: ["ramalan cuaca"], label: "artinya" },
  { front: "でんわばんごうあんない", answers: ["petunjuk nomor telepon"], label: "artinya" },
  { front: "いきます", answers: ["pergi"], label: "artinya" },
  { front: "きます", answers: ["datang"], label: "artinya" },
  { front: "かえります", answers: ["pulang"], label: "artinya" },
  { front: "がっこう", answers: ["sekolah"], label: "artinya" },
  { front: "スーパー", answers: ["swalayan", "pasar swalayan"], label: "artinya" },
  { front: "えき", answers: ["stasiun"], label: "artinya" },
  { front: "ひこうき", answers: ["pesawat terbang"], label: "artinya" },
  { front: "ふね", answers: ["kapal laut", "kapal"], label: "artinya" },
  { front: "でんしゃ", answers: ["kereta rel listrik", "kereta listrik"], label: "artinya" },
  { front: "ちかてつ", answers: ["kereta bawah tanah"], label: "artinya" },
  { front: "しんかんせん", answers: ["shinkansen"], label: "artinya" },
  { front: "バス", answers: ["bus"], label: "artinya" },
  { front: "タクシー", answers: ["taksi"], label: "artinya" },
  { front: "じてんしゃ", answers: ["sepeda"], label: "artinya" },
  { front: "あるいて", answers: ["berjalan kaki"], label: "artinya" },
  { front: "ひと", answers: ["orang"], label: "artinya" },
  { front: "ともだち", answers: ["teman"], label: "artinya" },
  { front: "かれ", answers: ["dia laki-laki"], label: "artinya" },
  { front: "かのじょ", answers: ["dia perempuan"], label: "artinya" },
  { front: "かぞく", answers: ["keluarga"], label: "artinya" },
  { front: "ひとりで", answers: ["sendirian", "dengan sendiri"], label: "artinya" },
  { front: "せんしゅう", answers: ["minggu lalu"], label: "artinya" },
  { front: "こんしゅう", answers: ["minggu ini"], label: "artinya" },
  { front: "らいしゅう", answers: ["minggu depan"], label: "artinya" },
  { front: "せんげつ", answers: ["bulan lalu"], label: "artinya" },
  { front: "こんげつ", answers: ["bulan ini"], label: "artinya" },
  { front: "らいげつ", answers: ["bulan depan"], label: "artinya" },
  { front: "きょねん", answers: ["tahun lalu"], label: "artinya" },
  { front: "ことし", answers: ["tahun ini"], label: "artinya" },
  { front: "らいねん", answers: ["tahun depan"], label: "artinya" },
  { front: "~ねん", answers: ["tahun ~"], label: "artinya" },
  { front: "なんねん", answers: ["tahun berapa"], label: "artinya" },
  { front: "~がつ", answers: ["bulan ~"], label: "artinya" },
  { front: "なんがつ", answers: ["bulan apa"], label: "artinya" },
  { front: "ついたち", answers: ["tanggal satu", "tanggal 1"], label: "artinya" },
  { front: "ふつか", answers: ["tanggal dua"], label: "artinya" },
  { front: "みっか", answers: ["tanggal tiga"], label: "artinya" },
  { front: "よっか", answers: ["tanggal empat"], label: "artinya" },
  { front: "いつか", answers: ["tanggal lima"], label: "artinya" },
  { front: "むいか", answers: ["tanggal enam"], label: "artinya" },
  { front: "なのか", answers: ["tanggal tujuh"], label: "artinya" },
  { front: "ようか", answers: ["tanggal delapan"], label: "artinya" },
  { front: "ここのか", answers: ["tanggal sembilan"], label: "artinya" },
  { front: "じゅうよっか", answers: ["tanggal empat belas"], label: "artinya" },
  { front: "はつか", answers: ["tanggal dua puluh"], label: "artinya" },
  { front: "にじゅうよっか", answers: ["tanggal dua puluh empat", "tanggal 24"], label: "artinya" },
  { front: "~にち", answers: ["tanggal ~", "~ hari"], label: "artinya" },
  { front: "なんにち", answers: ["tanggal berapa", "berapa hari"], label: "artinya" },
  { front: "いつ", answers: ["kapan"], label: "artinya" },
  { front: "たんじょうび", answers: ["ulang tahun", "hari ulang tahun"], label: "artinya" },
  { front: "そうですね", answers: ["ya betul", "ya begitulah"], label: "artinya" },
  { front: "どういたしまして", answers: ["sama sama"], label: "artinya" },
  { front: "~ばんせん", answers: ["peron nomor ~"], label: "artinya" },
  { front: "つぎの", answers: ["yang berikutnya"], label: "artinya" },
  { front: "ふつう", answers: ["biasa"], label: "artinya" },
  { front: "きゅうこう", answers: ["ekspres"], label: "artinya" },
  { front: "とっきゅう", answers: ["super ekspres", "ekspres super"], label: "artinya" },
  { front: "がんじつ", answers: ["tahun baru"], label: "artinya" },
  { front: "せいじんのひ", answers: ["hari perayaan menjadi dewasa", "hari kedewasaan"], label: "artinya" },
  { front: "けんこくきねんのひ", answers: ["hari pembangunan nasional", "hari peringatan berdirinya negara"], label: "artinya" },
  { front: "てんのうたんじょうび", answers: ["hari ulang tahun kaisar"], label: "artinya" },
  { front: "しゅんぶんのひ", answers: ["hari equinox musim semi"], label: "artinya" },
  { front: "しょうわのひ", answers: ["hari showa"], label: "artinya" },
  { front: "けんぽうきねんび", answers: ["hari peringatan konstitusi"], label: "artinya" },
  { front: "みどりのひ", answers: ["hari penghijauan"], label: "artinya" },
  { front: "こどものひ", answers: ["hari anak"], label: "artinya" },
  { front: "うみのひ", answers: ["hari bahari", "hari laut"], label: "artinya" },
  { front: "やまのひ", answers: ["hari gunung"], label: "artinya" },
  { front: "けいろうのひ", answers: ["hari hormat kepada orang tua"], label: "artinya" },
  { front: "しゅうぶんのひ", answers: ["hari equinox musim gugur"], label: "artinya" },
  { front: "スポーツのひ", answers: ["hari olahraga"], label: "artinya" },
  { front: "ぶんかのひ", answers: ["hari kebudayaan"], label: "artinya" },
  { front: "きんろうかんしゃのひ", answers: ["hari bersyukur untuk pekerjaan"], label: "artinya" },
].map(c => ({ ...c, type: "vocab" }));

export { VOCAB };
